### ISSUE TITLE
'source' not recognised

### ISSUE THREAD

**Issue by neiloliver57** [XeroAPI/xero-python-oauth2-starter#10]
Hi. I'm following the set up instructions and at the following, I get 'source' is not recognised as an internal or external command, ...
Activate new virtual environment by running source venv/bin/activate
What have I missed? Any ideas?
Many thanks

**Comment by SidneyAllen** [comment]
@neiloliver57 - sorry for the slow reply. 

Are you still having issues?

Have you've checked your version of python and confirmed it's version 3.5+

What happens when you open your terminal, cd to the /xero-python-oauth2-starter directory and 
run the command 'python3 -m venv venv'

That should allow you to run 'source venv/bin/activate'
